spring:
  application:
    name: sstu
  profiles:
    active: #spring.profiles.active#
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

