spring:
  profiles:
        active: prod
        include: swagger

  datasource:
      url: ${JDBC_DATABASE_URL}
      username: ${JDBC_DATABASE_USERNAME}
      password: ${JDBC_DATABASE_PASSWORD}

      driverClassName: org.postgresql.Driver
      maxActive: 10
      maxIdle: 5
      minIdle: 2
      initialSize: 5
      removeAbandoned: true