spring:
    profiles:
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:testdb
        username: sa
        password:

    h2:
        console:
            enabled: true
   jpa:
        database-platform: org.hibernate.dialect.H2Dialect\
        database: H2
        show-sql: true
        properties:
        hibernate:
          ddl-auto: create-drop
#            hibernate.id.new_generator_mappings: true
#            hibernate.cache.use_second_level_cache: true
#            hibernate.cache.use_query_cache: false
#            hibernate.generate_statistics: true